### PR TITLE
Merging in changes from web2preview

### PR DESCRIPTION
**Pull request by vduseev**
Hi @ludbek,

First of all, thank you for the wonderful library. Many people have been using it in production, reasearch, and home projects for years now. 

## Reason

I took a liberty of making a fork of `webpreview` with an initial intention of creating an independent project, based on the original one. But I'd like to propose to merge the changes back into `webpreview`.

The forked `web2preview` project is a small rewrite of your original code. It mainly focuses on making the codebase more extendable and fixing a couple of bugs. The reasoning behind the creation of the fork was based on the set of demands that have accumulated over years and were calling for a bigger change.

## What hasn't changed

I'd like to highlight that the fork has a complete compatibility with the original from the user's perpective.

* All existing API's and classes are preserved. 

  Functions such as `web_preview` function or `process_image_url`, `PreviewBase` class and the classes inherited from it are all in place in the same packages they were before. They all behave the same way before, throwing the same exceptions, or executing things in the familiar order. However, internally, they are now based on the slightly rewritten code.
  
  From the user's perspective nothing would change in their code when they upgrade.
  
* All existing tests are preserved. We can continue to rely on them as a guarantee that there are no regressions.

## What has changed

From the user's perspective, the following things have changed:

* Drop of Python 2 support.

  The end of life was 2.5 years ago. Also the previous versions are still going to be there in PyPI available for anyone still using Python 2 environment.
  
* When `content` of the page is passed, no `requests` calls are ever made. That enables users to use the library in a restricted environment, where no connection exists, but the content of the page is readily available (real case within our company).

* When parsing, the `web_preview` continues until it has collected title, description, and picture preview. 

  It does not stop on the first found or at somewhat complete result. Only if all methods are exhausted.
  
  An example of this would be this [Wiki Article](https://en.wikipedia.org/wiki/Enrico_Fermi) about Enrico Fermi. It only contains title and preview picture in OpenGraph schema, but does not contain the description meta tag. So, the algorithm now attempts all other approaches until it finds that it has collected all three fields: title, description, and image or until there are no extraction methods left to try anymore.
  
* New API's are added

  * `WebPreview` object that contains parsing results, behaves almost like a `dict` and serves as a basis for other classes.
  * `web2preview` function (to be renamed) returns `WebPreview` object instead of a tuple.
  
 * A simple CLI tool is added. It retrieves the three primary fields by calling the main parsing function.
 
 * Python Typing annotations have been added. That offers compatibility with `mypy` and automatically enables better syntax highlighting and suggestions in the modern code editors.

From the maintainer's perspective, these noticeable things have changed:

* Dependency management and release toolkit migrated to Poetry. 

  Poetry makes it easier to manage and update the dependencies, but it also adds nice tools for building and releasing 
  the package, managing virtual environments, and setting up command-line tools.
  
* CI/CD builds were moved GitHub Actions

  Many projects are migrating from Travis CI. Few years ago they were an undisputed leader and the primary choice for open source developers. However, scandals (exposed secret keys), price model changes, change of ownership of the company, and outdated tech behind the scenes are all major reasons for many project to move to GitHub Actions or GitLab CI/CD depending on where the project is hosted.

* Tox has been removed in favor of test strategy matrix in GitHub Actions.

  Due to its poor compatibility with `pyenv`
  
* Documentation have been updated with an added potential of generating Sphinx docs for readthedocs.io.

  Example: Google style function docs for `web2preview` function.
  
* Version of the library is now bumped and tagged using the `bump2version` CLI tooling.

* Code has been formatted with Black

* Test suite migrated to `pytest` as a modern alternative to traditional `unittests`

## Conclusion

I'd be happy to discuss any additional required changes and would be very grateful for your thoughts on this. This PR is far from the idea of the set of gradual changes, but that idea came as an afterthought, when the code had already too many changes.

There are several things still left to change in the forked copy before it can be considered to be merged:

* such as adding support for Pyhton 3.7 back.
* renaming the package, version, and some functions back to the old names.
* Additionally, a broader set of tests that would hit a 100% coverage mark wouldn't hurt.
* Covering the whole thing with a Sphinx like docs and generating a readthedocs site would be beneficial as well.

Looking forward to your feedback and thoughts!

### CODE REVIEW

**Comment by ludbek** [comment]
@vduseev Hey great to see your PR. Please give me 1 more day to look at this thoroughly.

**Comment by ludbek** [comment]
@vduseev LGTM. I reckon its ok to rename the instances of `web2preview` with `webpreview` before merge.

**Comment by vduseev** [comment]
@ludbek awesome! I'll start making changes to make sure the update is seamless and will double check that nothing breaks.

**Comment by vduseev** [comment]
@ludbek, thanks again for the opportunity to contriute!

I've merged the PR renaming every method to match the original and running tests before hand. Also, per your suggestion, the new `web2preview` method was renamed to `webpreview`.

All that's left to do is
* Release an updated version to PyPI
* To enable code-coverage badge. For that you'd need to
  * Create a free open-source [codecov.io](https://about.codecov.io/) account.
  * Add the project to your account.
  * Generate a `CODECOV_TOKEN`.
  * And finally, add it as a secret for GitHub actions through *Settings -> Secrets -> Actions -> Repository secrets*.

**Comment by ludbek** [comment]
@vduseev The package has come alive. Thank you. I will take care of the code coverage badge and the release workflow.

**Pull request merged**
